// Auto-generated CallTips dictionary
static const std::map<std::wstring, std::wstring> g_CallTipSignatures = {
    { L"ubind", L"ubind(double type) -> void" },
    { L"ulocate", L"ulocate(double locate, double flag, double enemy, double ore, double outY, double outFound, double outBuild) -> double" },
    { L"ucontrol", L"ucontrol(double type, double p1, double p2, double p3, double p4, double p5) -> void" },
    { L"control", L"control(double type, double target, double p1, double p2, double p3, double p4) -> void" },
    { L"getlink", L"getlink(double index) -> double" },
    { L"read", L"read(double target, double position) -> double" },
    { L"write", L"write(double target, double position, double value) -> void" },
    { L"sensor", L"sensor(double from, double type) -> double" },
    { L"radar", L"radar(double target1, double target2, double target3, double sort, double radar, double sortOrder) -> double" },
    { L"select", L"select(double op, double comp0, double comp1, double a, double b) -> double" },
    { L"end", L"end() -> void" },
    { L"draw", L"draw(double type, double x, double y, double p1, double p2, double p3, double p4) -> void" },
    { L"drawflush", L"drawflush(double target) -> void" },
    { L"print", L"print(double value) -> void" },
    { L"printchar", L"printchar(double value) -> void" },
    { L"format", L"format(double value) -> void" },
    { L"printflush", L"printflush(double target) -> void" },
    { L"setrate", L"setrate(double amount) -> void" },
    { L"wait", L"wait(double value) -> void" },
    { L"stop", L"stop() -> void" },
    { L"lookup", L"lookup(double from, double type) -> double" },
    { L"packcolor", L"packcolor(double r, double g, double b, double a) -> double" },
    { L"unpackcolor", L"unpackcolor(double r, double g, double b, double a, double value) -> void" },
    { L"cutscene", L"cutscene(double action, double p1, double p2, double p3, double p4) -> void" },
    { L"fetch", L"fetch(double type, double team, double extra, double index) -> double" },
    { L"query", L"query(double shape, double type, double team, double x, double y, double width, double height) -> void" },
    { L"getblock", L"getblock(double x, double y, double layer) -> double" },
    { L"setblock", L"setblock(double x, double y, double block, double team, double rotation, double layer) -> void" },
    { L"spawnunit", L"spawnunit(double type, double x, double y, double rotation, double team, double effect) -> double" },
    { L"spawnbullet", L"spawnbullet(double from, double index, double x, double y, double rotation, double team, double owner, double damage, double velocityScl, double lifeScl, double aimX, double aimY) -> double" },
    { L"setweather", L"setweather(double type, double state) -> void" },
    { L"applyeffect", L"applyeffect(double clear, double effect, double unit, double duration) -> void" },
    { L"setrule", L"setrule(double rule, double value, double p1, double p2, double p3, double p4) -> void" },
    { L"flushmessage", L"flushmessage(double type, double duration, double outSuccess) -> void" },
    { L"effect", L"effect(double type, double x, double y, double rotation, double color, double data) -> void" },
    { L"explosion", L"explosion(double team, double x, double y, double radius, double damage, double air, double ground, double pierce, double effect) -> void" },
    { L"sync", L"sync(double variable) -> void" },
    { L"clientdata", L"clientdata(double channel, double value, double reliable) -> void" },
    { L"getflag", L"getflag(double flag) -> double" },
    { L"setflag", L"setflag(double flag, double value) -> void" },
    { L"spawnwave", L"spawnwave() -> void" },
    { L"setprop", L"setprop(double type, double of, double value) -> void" },
    { L"playsound", L"playsound() -> void" },
    { L"playmusic", L"playmusic() -> void" },
    { L"setmarker", L"setmarker(double type, double id, double p1, double p2, double p3) -> void" },
    { L"makemarker", L"makemarker(double type, double id, double x, double y, double replace) -> void" },
    { L"localeprint", L"localeprint(double name) -> void" },
};
