name: MSBuild

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build mIDE
      run: |
        msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.BUILD_PLATFORM }} mIDE/mIDE.vcxproj

    - name: Upload mIDE.exe Binary
      uses: actions/upload-artifact@v4
      with:
        name: mIDE-windows-x64
        path: |
          x64/Release/mIDE.exe
          mIDE/x64/Release/mIDE.exe
        if-no-files-found: warn
